### ISSUE TITLE
Can't Delete a test member from ghost after deleting the customer on stripe

### ISSUE THREAD

**Issue by oreniko26** [TryGhost/Ghost#11557]
Summary:
A test user whose associated stripe test customer has been deleted cannot be deleted.

Steps to reproduce:
1. sign up on your ghost site.
2. subscribe to any membership using stripe test API keys.
3. go to the /ghost admin endpoint and select members.
4. select that member and then select their stripe customer.
5. delete the customer on stripe.
6. click on delete member on ghost admin.

Expected result: admins should be able to delete members regardless of Stripe membership.
Actual result: on version 3.3.0 I used to get 500 and that "message" can't be undefined.
On 3.4.0 which I updated to since it included a crucial fix to Lyra, I simply get 404.

I would appreciate a fix to this as I'm on the cusp of importing my entire email list to the site as subscribers.
I'm on ubuntu, self-hosting on AWS. Let me know if you need any more information and I'll include what I can.

**Comment by gargol** [comment]
Hi @oreniko26 have put this into our backlog. Will update when it's prioritized to be worked on.

**Comment by lunaticmonk** [comment]
I couldn't reproduce this. I am able to delete the customer successfully in the latest version. Is this fixed in any of the patches done recently?

**Comment by gargol** [comment]
@oreniko26 are you still experiencing this issue?

**Comment by oreniko26** [comment]
Still getting a 'resource not found' error. Did you try to delete the member's associated stripe info before deleting them in ghost?

**Comment by lunaticmonk** [comment]
@oreniko26 Here is what I did:

1. I subscribed to the blog and paid with stripe.
2. The member appeared in the members tab in ghost admin.
![image](https://user-images.githubusercontent.com/17925669/80176145-43506980-8615-11ea-9149-c833d4204b3c.png)

3. Then, I went to stripe dashboard and deleted the test customer from there.
![image](https://user-images.githubusercontent.com/17925669/80176160-4a777780-8615-11ea-9815-0f4e7c0b42a7.png)


4. Came back to ghost admin and deleted the member from there. It got deleted.

![image](https://user-images.githubusercontent.com/17925669/80176199-6d099080-8615-11ea-84d6-e0a2f8a1da2b.png)


The only thing I am concerned here is that when I subscribed to the blog by paying via stripe, the stripe info did not appear in the member tab in ghost. I mean the following:

![image](https://user-images.githubusercontent.com/17925669/80176192-68dd7300-8615-11ea-840f-95d2fd229981.png)

Not sure if the above is the reason.

**Comment by ErisDS** [comment]
This should not be picked up until we've clarified members delete behaviour, as it may go away as part of changing that instead.

**Comment by SaurabhPGunjal** [comment]
I'm facing the exact same issue. Is there a way to delete the member from the backend?

https://forum.ghost.org/t/help-unable-to-delete-member/15743

**Comment by SaurabhPGunjal** [comment]
Anyone facing the same issue -
I solved it by going to :

`sudo mysql -u ghost -p`
*enter password* (You'll get this in the ghost config file)

```
show databases
USE ghost_production
``` (if 'ghost_production' is the name of your db)
`show tables`

navigate to tables and delete all entries from  'members_stripe_customers_subscriptions'


Use basic commands from this -

https://dev.mysql.com/doc/mysql-getting-started/en/

(I figured it out myself by googling, surfing YT videos after tirelessly requesting on the forum and github. Posting the solution here so you don't have to go through all this.) :)
