### ISSUE TITLE
Issue updating to version 5.53.0

### ISSUE THREAD

**Issue by sergiospagnuolo** [TryGhost/Ghost#17125]
### Issue Summary

I am getting an error while trying to update ghost to v5.53.0

### Steps to Reproduce

1. `ghost update` in the CLI 

### Ghost Version

5.52.0

### Node.js Version

v16.14.2

### How did you install Ghost?

ghost install

### Database type

MySQL 5.7

### Relevant log / error output

```shell
✔ Fetched release notes
✔ Downloading and updating Ghost to v5.53.0
+ sudo systemctl stop ghost_134-122-29-55
✔ Stopping Ghost
✔ Linking latest Ghost and recording versions
+ sudo systemctl start ghost_134-122-29-55
+ sudo systemctl stop ghost_134-122-29-55
✖ Restarting Ghost
A GhostError occurred.

Message: Ghost was able to start, but errored during boot with: alter table `collections_posts` add constraint `collections_posts_collection_id_foreign` foreign key (`collection_id`) references `collections` (`id`) on delete CASCADE - Failed to open the referenced table 'collections'
Help: Error occurred while executing the following migration: 2023-06-20-10-18-add-collections-posts-table.js
Suggestion: journalctl -u ghost_134-122-29-55 -n 50

Debug Information:
    OS: Ubuntu, v20.04.4 LTS
    Node Version: v16.14.2
    Ghost Version: 5.53.0
    Ghost-CLI Version: 1.24.0
    Environment: production
    Command: 'ghost update'

Additional log info available in: /home/ghost-mgr/.ghost/logs/ghost-cli-debug-2023-06-23T16_22_07_869Z.log

Try running ghost doctor to check your system for known issues.

You can always refer to https://ghost.org/docs/ghost-cli/ for troubleshooting.
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by nebulade** [comment]
While running the e2e tests for the Cloudron package, we also found this issue. Just adding a bit more logs to it:

```
19:13:46 - [2023-06-23 17:13:46] INFO Finished database init!
19:13:48 - [2023-06-23 17:13:47] INFO Creating database backup
19:13:48 - [2023-06-23 17:13:48] INFO Database backup written to /app/data/content/data/cloudron-ghost-blog.ghost.2023-06-23-17-13-48.json
19:13:48 - [2023-06-23 17:13:48] INFO Running migrations.
19:13:48 - [2023-06-23 17:13:48] INFO Adding table: temp_mail_events
19:13:48 - [2023-06-23 17:13:48] INFO Adding table: collections_posts
19:13:48 - [2023-06-23 17:13:48] INFO Rolling back: alter table `collections_posts` add constraint `collections_posts_collection_id_foreign` foreign key (`collection_id`) references `collections` (`id`) on delete CASCADE - Failed to open the referenced table 'collections'.
19:13:48 - [2023-06-23 17:13:48] INFO Dropping table: collections_posts
19:13:48 - [2023-06-23 17:13:48] INFO Dropping table: temp_mail_events
19:13:48 - [2023-06-23 17:13:48] INFO Rollback was successful.
19:13:48 - [2023-06-23 17:13:48] ERROR alter table `collections_posts` add constraint `collections_posts_collection_id_foreign` foreign key (`collection_id`) references `collections` (`id`) on delete CASCADE - Failed to open the referenced table 'collections'
19:13:48 - 
19:13:48 - alter table `collections_posts` add constraint `collections_posts_collection_id_foreign` foreign key (`collection_id`) references `collections` (`id`) on delete CASCADE - Failed to open the referenced table 'collections'
19:13:48 - 
19:13:48 - {"config":{"transaction":false},"name":"2023-06-20-10-18-add-collections-posts-table.js"}
19:13:48 - "Error occurred while executing the following migration: 2023-06-20-10-18-add-collections-posts-table.js"
19:13:48 - 
19:13:48 - Error ID:
19:13:48 - 300
19:13:48 - 
19:13:48 - Error Code: 
19:13:48 - ER_FK_CANNOT_OPEN_PARENT
19:13:48 - 
19:13:48 - ----------------------------------------
19:13:48 - 
19:13:48 - Error: alter table `collections_posts` add constraint `collections_posts_collection_id_foreign` foreign key (`collection_id`) references `collections` (`id`) on delete CASCADE - Failed to open the referenced table 'collections'
19:13:48 - at /home/cloudron/ghost/versions/5.53.0/node_modules/knex-migrator/lib/index.js:1032:19
19:13:48 - at Packet.asError (/home/cloudron/ghost/versions/5.53.0/node_modules/mysql2/lib/packets/packet.js:728:17)
19:13:48 - at Query.execute (/home/cloudron/ghost/versions/5.53.0/node_modules/mysql2/lib/commands/command.js:29:26)
19:13:48 - at Connection.handlePacket (/home/cloudron/ghost/versions/5.53.0/node_modules/mysql2/lib/connection.js:489:32)
19:13:48 - at PacketParser.onPacket (/home/cloudron/ghost/versions/5.53.0/node_modules/mysql2/lib/connection.js:94:12)
19:13:48 - at PacketParser.executeStart (/home/cloudron/ghost/versions/5.53.0/node_modules/mysql2/lib/packet_parser.js:75:16)
19:13:48 - at Socket.<anonymous> (/home/cloudron/ghost/versions/5.53.0/node_modules/mysql2/lib/connection.js:101:25)
19:13:48 - at Socket.emit (node:events:513:28)
19:13:48 - at addChunk (node:internal/streams/readable:324:12)
19:13:48 - at readableAddChunk (node:internal/streams/readable:297:9)
19:13:48 - at Readable.push (node:internal/streams/readable:234:10)
19:13:48 - at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by daniellockyer** [comment]
Thanks both - this snook in just prior to the release and no tests found it 😢 A fix is in progress

**Comment by daniellockyer** [comment]
This is fixed in v5.53.1 🙂

**Comment by sergiospagnuolo** [comment]
that was fast. tks, Daniel! will test it out now.

**Comment by PhillipMwaniki** [comment]
The issue isn't fixed for me after making the update to version 5.53.1

**Ghost Version**

5.53.1

**Node.js Version**

v16.14.2

**How did you install Ghost?**

Digital Ocean server template set up

**Database type**

MySQL 5.7
