### ISSUE TITLE
Deletion of the final character of a link within a Toggle card can delete the entire link

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#18903]
### Issue Summary

Deleting the final character of a link in a Toggle card can delete the entire link. Sometimes, but not always. Because as seen in the video below, when I successfully deleted (and then un-did) the deletion of characters within a link I was able to move the cursor to the final character and successfully delete it (and nothing else). But when I moved the cursor away from the link and then returned to the position enabling me to delete the final character of the link, doing so once again deletes the entire link.

https://github.com/TryGhost/Ghost/assets/27488257/1669cf81-b385-488d-8b8b-92372e8c1637

@9larsons This is a repeat of [this issue that you fixed](https://github.com/TryGhost/Ghost/issues/18674) within the general space of the editor. Not sure if it occurs anywhere else besides this.

### Steps to Reproduce

1. Place the cursor a few characters after the final character after a link within a toggle card, then move it to just after the final character of a link
2. Press the delete button
3. See the entire link disappear

### Ghost Version

5.71.2+moya

### Node.js Version

Yes

### How did you install Ghost?

Ghost(Pro)

### Database type

MySQL 5.7

### Browser & OS version

Firefox 119, macOS 13.6

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by 9larsons** [comment]
I believe this is resolved with our changes in `5.72.1`. Could you try with the newer version or wait for next week's rollout to confirm?

**Comment by stromfeldt** [comment]
Whoops, my mistake @9larsons. The video from up above was from my local 5.72.1 instance, and now that my Ghost(Pro) instance has been updated to 5.72.1 I tried it there as well and the problem persists.

**Comment by 9larsons** [comment]
https://github.com/TryGhost/Ghost/assets/21961100/ed90b2e7-7fa8-4bb3-8041-8e9a24338050

Any tips on what I'm not doing to be able to reproduce?

**Comment by 9larsons** [comment]
This is only impacting Firefox, afaict. The root cause is an upstream issue that I'll open up but we've got a workaround for the moment.

**Comment by stromfeldt** [comment]
Thanks for that. I was confused why we had different results, and was gonna wait for 5.73.1 before trying things out again, but I see you've narrowed it down.
