### ISSUE TITLE
GScan on gscan.ghost.org does not recognise {{recommendations}} and {{readable_url}} helper

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#19317]
### Issue Summary

The local version of GScan 4.42.0 correctly recognizes the helpers mentioned in the title, however, the version on [gscan.ghost.org](https://gscan.ghost.org) reports the following errors:

![Zrzut ekranu 2023-12-11 o 18 11 17](https://github.com/TryGhost/Ghost/assets/23366922/93655471-c103-4e16-8c3d-3aaff3e8f7ec)

The `{{readable_url}}` helper is not recognized in every context, whereas from what I could observe, the `{{recommendations}}` helper is reported as 'missing' when used with the 'limit' attribute, like `limit="10"` >> https://ghost.org/docs/themes/helpers/recommendations/#limit

### Steps to Reproduce

Add the `{{recommendations limit="10"}}` helper and `{{readable_url}}` to the theme, and upload it to [gscan.ghost.org](https://gscan.ghost.org)

### Ghost Version

not applicable

### Node.js Version

not applicable

### How did you install Ghost?

not applicable

### Database type

Other

### Browser & OS version

all

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Thanks for the issue @fueko! The service needed a kick to pick up the new version - so this should be fixed 🙂

**Comment by fueko** [comment]
Hi @daniellockyer!

Unfortunately, this problem still occurs, is there any chance to fix the Web GScan version so that it is compatible with the CLI version?
