### ISSUE TITLE
can't return to previous page after deleting post

### ISSUE THREAD

**Issue by JaydenForYou** [TryGhost/Ghost#19408]
### Issue Summary

can't return to previous page after deleting post

### Steps to Reproduce

1. enther the edit page
2. delete post
3. there was no response after pressing the return button 
![1703646664491](https://github.com/TryGhost/Ghost/assets/53374430/1676f02b-8f3a-4c2c-b822-1707f560a930)
5. console log as follow
![1703646688000](https://github.com/TryGhost/Ghost/assets/53374430/ece7485d-c14b-43d1-be64-2bb5363037b9)

### Ghost Version

latest

### Node.js Version

18.x

### How did you install Ghost?

Ubuntu Server 22.04 LTS

### Database type

MySQL 8

### Browser & OS version

Chrome

### Relevant log / error output

```shell
vendor-f6856af9fcd8ab6533f2a4339ececbc8.js:6449 Uncaught (in promise) Error: Attempted to set 'lexical' on the deleted record <post:656e0e57d732aa747eb28169>
    at Ye.setDirtyAttribute (vendor-f6856af9fcd8ab6533f2a4339ececbc8.js:6449:318)
    at e.set (vendor-f6856af9fcd8ab6533f2a4339ececbc8.js:5914:244)
    at Me._set (vendor-f6856af9fcd8ab6533f2a4339ececbc8.js:1194:9)
    at Me.set (vendor-f6856af9fcd8ab6533f2a4339ececbc8.js:1190:16)
    at e.r [as lexical] (vendor-f6856af9fcd8ab6533f2a4339ececbc8.js:1149:310)
    at Oe (vendor-f6856af9fcd8ab6533f2a4339ececbc8.js:1172:37)
    at vendor-f6856af9fcd8ab6533f2a4339ececbc8.js:1169:19
    at Oe (vendor-f6856af9fcd8ab6533f2a4339ececbc8.js:1170:103)
    at ge.set (vendor-f6856af9fcd8ab6533f2a4339ececbc8.js:1730:151)
    at ge.beforeSaveTask (ghost-2fe51d0831dd1694a4e88abd5f38e2fb.js:2502:124)
```

### Code of Conduct

- [x] I agree to be friendly and polite to people in this repository

**Comment by Anilpandiya** [comment]
Hello @JaydenForYou 

I tried to reproduce the issue but it seems working fine. Please double-check if the issue persists.

**Comment by yannickcof** [comment]
yannick coffi

https://snubmonkey.com
https://ocularfuel.com
https://prints.yannickcoffi.com
https://yannickcoffi.com
https://luloutaste.com

**Comment by JaydenForYou** [comment]
> Is this still reproducible? [A related fix](https://github.com/TryGhost/Ghost/pull/19369) was included in the 5.76.0 release and I've been unable to reproduce in my own tests.

[confirmed]bug fixed in the 5.76.0.thanks.

**Comment by danielraffel** [comment]
This bug was marked as a duplicate of #19563 however it is still reproductive in ghost 5.79.0

**Comment by danielraffel** [comment]
> Is this still reproducible? [A related fix](https://github.com/TryGhost/Ghost/pull/19369) was included in the 5.76.0 release and I've been unable to reproduce in my own tests.

Yea I can reproduce in #19563 in ghost 5.79.0

**Comment by mfitzp** [comment]
I've just created a new site on Ghost Pro & still see this bug. However, I imported the articles from another install. Perhaps there is something in the imported articles that is causing this? If I create a new post from scratch, and then delete that, there is no error.

The traceback is 

```js
Uncaught (in promise) Error: Attempted to set 'lexical' on the deleted record <post:65d20658f6311b0001575eb6>
    at Ye.setDirtyAttribute (-private.js:4752:1)
    at e.set (-private.js:148:1)
    at Me._set (index.js:1776:1)
    at Me.set (index.js:1727:1)
    at e.r [as lexical] (index.js:878:1)
    at Oe (index.js:1327:1)
    at index.js:1357:1
    at Oe (index.js:1323:1)
    at we.set (observable.js:172:1)
    at we.beforeSaveTask (lexical-editor.js:544:1)
    at beforeSaveTask.next (<anonymous>)
    at e.GeneratorState.step (generator-state.js:28:1)
    at e.TaskInstanceExecutor.generatorStep (executor.js:243:1)
    at e.TaskInstanceExecutor.handleResolvedContinueValue (executor.js:123:1)
    at e.TaskInstanceExecutor.proceedSync (executor.js:87:1)
    at e.TaskInstanceExecutor.start (executor.js:39:1)
    at i.start (base.js:56:1)
    at refresh.js:23:1
    at Array.forEach (<anonymous>)
    at e.default.process (refresh.js:23:1)
    at r.refresh (scheduler.js:47:1)
    at r.perform (scheduler.js:39:1)
    at a._performShared (task.js:68:1)
    at a._perform (task.js:56:1)
    at we.saveTask (lexical-editor.js:467:1)
    at saveTask.next (<anonymous>)
    at e.GeneratorState.step (generator-state.js:28:1)
    at e.TaskInstanceExecutor.generatorStep (executor.js:243:1)
    at e.TaskInstanceExecutor.handleResolvedContinueValue (executor.js:123:1)
    at e.TaskInstanceExecutor.proceedSync (executor.js:87:1)
    at e.TaskInstanceExecutor.start (executor.js:39:1)
    at i.start (base.js:56:1)
    at refresh.js:23:1
    at Array.forEach (<anonymous>)
    at e.default.process (refresh.js:23:1)
    at r.refresh (scheduler.js:47:1)
    at r.perform (scheduler.js:39:1)
    at a._performShared (task.js:68:1)
    at a._perform (task.js:56:1)
    at we.autosaveTask (lexical-editor.js:408:1)
    at autosaveTask.next (<anonymous>)
    at e.GeneratorState.step (generator-state.js:28:1)
    at e.TaskInstanceExecutor.generatorStep (executor.js:243:1)
    at e.TaskInstanceExecutor.handleResolvedContinueValue (executor.js:123:1)
    at e.TaskInstanceExecutor.proceedSync (executor.js:87:1)
    at e.TaskInstanceExecutor.start (executor.js:39:1)
    at i.start (base.js:56:1)
    at refresh.js:23:1
    at Array.forEach (<anonymous>)
    at e.default.process (refresh.js:23:1)
```

**Comment by AbdoCode** [comment]
Bug still exists in ghost 5.81.1
