### ISSUE TITLE
JWKS exposed under /members/.well-known/jwks.json provides invalid key length for Member JWTs

### ISSUE THREAD

**Issue by the-leonat** [TryGhost/Ghost#24831]
### Issue Summary

When verifying JWT member tokens, the JSON webtoken keyset (JWKS) exposed at `/members/.well-known/jwks.json` does not provide a public key of sufficient length to validate said tokens.

The issued member token header, retrieved from `members/api/session/` looks like this:
```json
{
  "alg": "RS512",
  "typ": "JWT",
  "kid": "redacted"
}
```
According to the official spec, RS512 requires the RSA key modulus length to be 2048 bits or larger. The current key exposed by Ghost’s JWKS endpoint appears to be smaller than this, resulting in the following error when verifying tokens with a compliant library like `jose`:
```
Error: RS512 requires key modulusLength to be 2048 bits or larger
```

### Steps to Reproduce

Grab a member token at `/member/api/session` and JSON web key at `/members/.well-known/jwks.json`. Make sure to use just the JSON Web Key, excluding the array. 

```json
{"kty":"RSA","kid":"2B9asCdRsVD1PorgY7K8KnJ3dF_0FB3v_3qM6pu00Y8","n":"o66I-4QwmERPboZwnhS6exwhZFRohZVOw_AK74C4BbwavIaCl-P0ZObJBnFcl7AWmNhFSRwDdg1L35CwNLMxhnzvmaLgu0qw4XrIFjFnPIV66zCt9HBSZk2fNQ0IN1bomUA7OQxe_Eou0_YNa-l9ZnfQnVnBIChaXALv89kSmaM","e":"AQAB"}
```

Enter into a validation site like `https://www.jwt.io/` and get the following error:

```
RS512 requires key modulusLength to be 2048 bits or larger
```

### Ghost Version

5.*, 6.*

### Node.js Version

22

### How did you install Ghost?

both locally as well as on servers installed via docker and ghost pro.

### Database type

MySQL 5.7

### Relevant log / error output

```shell

```

### Code of Conduct

- [x] I agree to be friendly and polite to people in this repository

**Comment by cathysarisky** [comment]
Just popping in to confirm that I am hitting the same problem.  Jose refuses to validate Ghost's tokens because of RS512 requiring a longer key.  Jsonwebtoken apparently doesn't enforce this (which might be a workaround for the OP), but doesn't help me because I'm running on deno...

**Comment by gitcedric** [comment]
Hey,

+1 - Running into this with Ghost 6.13.2 in Docker.                                                                                                          
                                                                                                                                                               
I am building a tool form that validates Ghost member JWTs server-side. The jose library rejects the 1024-bit keys.

**Comment by the-leonat** [comment]
Shouldn't this be fixed by #24958 ? I did not have the time to test it myself.
My work around is to export the key from the JsonWebKeySet Endpoint with jose and validate the payload with `jsowebtoken`.

```typescript
import { exportSPKI, importJWK } from "jose"


async function getJWKS(cache: KVNamespace, ghostUrl: string) {
    const result = await fromCache(
        cache,
        `jwks`,
        async () => {
            const res = await fetch(`${ghostUrl}/members/.well-known/jwks.json`)
            const json = await res.json()

            return json
        },
        60 * 60 * 24,
    )

    if (
        !(typeof result == "object" && !!result && "keys" in result && Array.isArray(result.keys))
    ) {
        console.error("error in jwks", result)
        throw new Error("error in jwks")
    }
    const key = await importJWK(
        {
            ...result.keys[0],
            ext: true,
        },
        "RS512",
    )
    if (!(key instanceof CryptoKey)) {
        throw new Error("not instance of crypto key")
    }

    const pem = await exportSPKI(key)
    return pem
}
```

verify with 

```typescript
import { verify } from "jsonwebtoken"
verify(identity, pem, { algorithms: ["RS512"] })
```

**Comment by caseyschorr** [comment]
+1. Still broken.

I'm a Ghost(Pro) subscriber building an external app integration against the new `/members/api/entitlements` JWT endpoint from PR #26523, and today I hit the JWKS key-size issue described here on Ghost(Pro).

My use case is exactly what the entitlement JWT seems designed for: a logged-in Ghost member’s browser fetches `/members/api/entitlements`, sends that short-lived JWT to my Cloudflare Worker API, and the Worker verifies the token before issuing its own app session. This lets the external app trust Ghost membership/entitlement state without storing a Ghost Admin API key or trusting browser-supplied member IDs.

The entitlement JWT itself looks good in my staging test:

- `alg`: `RS512`
- `kid`: matches `/members/.well-known/jwks.json`
- `iss`: `https://www.ghost-pro-website.dev/members/api`
- `aud`: `https://www.ghost-pro-website.dev/members/api`
- `scope`: `members:entitlements:read`
- `paid`: boolean `true`
- `member_uuid`: present
- lifetime: 300 seconds

However, verification with `jose` fails because the RSA modulus in the published members JWKS is 1024-bit. `jose` requires RS512 RSA keys to be 2048 bits or larger, which matches the security expectations for modern RS* JWT verification.

This blocks using the entitlement JWT with a standards-oriented verifier in Cloudflare Workers. I can work around it temporarily with a custom verifier that accepts the current 1024-bit key, but I would strongly prefer not to ship that as the long-term security boundary for member-authenticated app data.

Would the Ghost team consider rotating/regenerating the members JWT signing key so `/members/.well-known/jwks.json` publishes a 2048-bit-or-larger RSA key for RS512 tokens?

That would make the entitlement JWT endpoint much more practical for external app/session integrations while avoiding the need for custom or less strict verification code.

Thanks for adding this endpoint. It is very close to being exactly the right primitive for Ghost-to-external-app auth.

**Comment by jameslcowan** [comment]
Picking this up — I'm opening a PR that:

- Bumps **default** `members_*` / `ghost_*` JWT signing key generation to **2048-bit RSA** (RS512-compatible)
- Adds a migration that **updates** existing key settings in place when they're still 1024-bit (not `removeSetting` + hope they come back — learned from the feedback on #24958)

**Scope clarification:** this only rotates JWT signing keys stored in `settings` (`members_private_key`, `members_public_key`, `ghost_private_key`, `ghost_public_key`). It does **not** touch Admin API keys, custom integration keys, or rows in `api_keys`.

**Expected impact:** logged-in members may need to sign in again after upgrade; magic links issued before the migration won't verify. External apps using `/members/.well-known/jwks.json` with `jose` should work afterward.

If the team prefers a dual-key JWKS rollover (publish old + new public keys for a window) instead of a hard cutover, happy to adjust — just let me know.

**Comment by the-leonat** [comment]
Is this fixed now?
