### ISSUE TITLE
{{ghost_head}} and {{meta_title}} issues

### ISSUE THREAD

**Issue by viruzx** [TryGhost/Ghost#6139]
Ghost head and meta title are outputted weirdly into my HTML.

I have nothing special in ghost head and meta title should be KNYZ Labs but instead it's `__aSyNcId_&lt;_bYzx_PJd__` and `__aSyNcId_&lt;_bWSQWKuW__` respectively.

**Comment by ErisDS** [comment]
@viruzx Have you enabled the new beta features? Please, either file a full bug report or use slack If you just need help, otherwise it is very hard to help.

**Comment by viruzx** [comment]
@ErisDS I don't have time for a full bug report ATM and as for slack someone already seemed to have a similar issue with tags outputting gibberish.

**Comment by mwo44** [comment]
It seems that this bug appear when a {{post_class}} shortcode is used in home.hbs template.

**Comment by ErisDS** [comment]
This is fixed in 0.7.3

**Comment by mwo44** [comment]
Nope, have just updated the Ghost and the issue with {{post_class}} still occurs, sorry.

**Comment by ErisDS** [comment]
Yeah - discovered a further issue, there's already a commit in master to fix it.

**Comment by mwo44** [comment]
You rock!
