### ISSUE TITLE
Image upload 401 in version 0.8

### ISSUE THREAD

**Issue by klaaz0r** [TryGhost/Ghost#6884]
### Issue Summary

Once I upload an image I get a 401 in the console and an Access denied notification,  I had similar problems with rocket loader from cloud flare before but on this blog no services are used. On one of the closed issues I red a bug with version 0.7.5 that looks the same but was fixed. 

### Steps to Reproduce

1. Upload image from file explorer 
2. "Access denied" notification 

### Technical details:

* Ghost Version: 0.8
* Browser/OS: Chrome/OSX

**Comment by kevinansfield** [comment]
@klaaz0r is this for every image? does the problem persist after a refresh or when using an Incognito session?

Some screenshots of the web inspector console showing the error and the error in the Network tab of web inspector would be useful if you are able to provide them. Thanks!

**Comment by CairoLee** [comment]
I have the same problem. Upload new photo in the post is work fine.
Buy if i try to upload a "Blog Logo" in the Admin dashboard, will show "Access Denied."

![access-denied](https://cloud.githubusercontent.com/assets/4458917/15501455/23075082-21e0-11e6-8965-5f34bef5338a.png)

##### Nginx log

> 114.241.24.224 - - [24/May/2016:18:44:27 +0800] "POST /ghost/api/v0.1/uploads/ HTTP/1.1" 401 73 "http://ghost.rathena.cn/ghost/settings/general/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) ghost-desktop/0.4.0 Chrome/47.0.2526.110 Electron/0.36.12 Safari/537.36"
> 114.241.24.224 - - [24/May/2016:18:45:11 +0800] "POST /ghost/api/v0.1/uploads/ HTTP/1.1" 401 73 "http://ghost.rathena.cn/ghost/settings/general/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) ghost-desktop/0.4.0 Chrome/47.0.2526.110 Electron/0.36.12 Safari/537.36"

##### Environment

- CentOS 6.5 x64
- Ghost v0.8.0
- npm 1.3.6
- node v0.10.42

I try to run:
```
chown -R root:root /data/htdocs/ghost
```
but not working.

**Comment by CairoLee** [comment]
Sorry, i restart the Ghost Desktop(Mac), the problem is solved.

Maybe the session is expired (but if really the session is expired, why i can update the post with no problem?)

**Comment by klaaz0r** [comment]
@kevinansfield it still happens after a refresh / cache clean / cookies

**Comment by ErisDS** [comment]
@klaaz0r are you also using Ghost Desktop? 

cc @CairoLee if you're having problems with Ghost Desktop that you cannot also reproduce in the web version, you'll need to raise the issue over on the [Ghost Desktop](https://github.com/TryGhost/Ghost-Desktop) repository.

**Comment by CairoLee** [comment]
Okay, got it.
Thank you @ErisDS  XD
