### ISSUE TITLE
Bug: Theme & Import Zip uploads do not work on Windows

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#7292]
Uploading a zip file to either the theme uploader or the importer is not working on Windows.

### Steps to Reproduce

1. Use Windows (any browser, even Chrome)
2. Try to upload a zip file to the theme uploader

This has been tracked down to an issue in Ember, but I also believe the `application/x-zip-compressed` mimetype needs to be permitted in the validator as it is in the importer: 

https://github.com/TryGhost/Ghost/blob/663b410fd4f2f5960f6c600d2efea2edf3867ccd/core/server/data/importer/index.js#L28-L28

https://github.com/TryGhost/Ghost/blob/587337aab365733a3a75abc105a43f307561f493/core/server/config/index.js#L280-L280

### Technical Details

This has been confirmed on Windows 7 & 8

**Comment by kirrg001** [comment]
This was fixed via https://github.com/TryGhost/Ghost-Admin/pull/238 and #7293.

**Comment by ErisDS** [comment]
Reopening this as I have received a report that this is still not working.

The report was on Ghost(Pro), using Windows 7, tried in both chrome and firefox. 

From a quick Google, I can't find any additional mimetypes we might be missing. I only have access to Windows 10 at the moment, and cannot reproduce the problem. 

It would be good to review this again for the 0.11.0 release to see if we can find any edge cases.

**Comment by acburdine** [comment]
From #7357 - this error may be occurring on Ubuntu systems as well. Going to download an Ubuntu image later today so I can verify that it is an issue.

**Comment by vasanthdeveloper** [comment]
This issue still persists today!
https://forum.ghost.org/t/ghost-says-invalid-zip-when-upload-my-theme/4001/2
