### ISSUE TITLE
Previously published drafts are listed before new drafts

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8495]
### Issue Summary

Any drafts that were previously published or have had their "published at" date manually set will be ordered above new drafts. In this example you can see the newly created draft appearing 2nd in the list despite the top post being created a few days ago and having been last edited a few hours earlier than the new post was created:

<img width="392" alt="screen shot 2017-05-30 at 15 59 57" src="https://cloud.githubusercontent.com/assets/415/26591311/2d98cc62-4555-11e7-820d-5fc0897ab369.png">

### Steps to Reproduce

1. Create a new post
2. Publish the post then unpublish it to make it a draft again
3. Go the the posts list, note that it's at the top of the list
4. Create a new post and keep it as a draft
5. Go back to the posts list, note that your new post is in 2nd position rather than 1st position

### Technical details:

* Ghost Version: 1.0 alpha 21
* Node Version: 6.10.1
* Database: SQLIte

**Comment by kevinansfield** [comment]
Ensuring `published_at` is ignored for draft ordering would involve a quick change to the default order:

```
    orderDefaultRaw: function () {
        return '' +
            'CASE WHEN posts.status = \'scheduled\' THEN 1 ' +
            'WHEN posts.status = \'draft\' THEN 2 ' +
            'ELSE 3 END ASC,' +
            'CASE WHEN posts.status != \'draft\' THEN posts.published_at END DESC,' +
            'posts.updated_at DESC,' +
            'posts.id DESC';
    },
```

If that's the desired behaviour any solution should also add tests etc 😄

**Comment by stefanovazzocell** [comment]
I'm experiencing the same problem. A post I already posted is listed as a draft.
The problems seemed to start with Ghost 1.9.1 and 1.10.0.

**Comment by kevinansfield** [comment]
@stefanovazzocell that sounds like a different issue, maybe #9072? That was fixed in 1.10.0.

**Comment by stefanovazzocell** [comment]
@kevinansfield  I am still experiencing it in 1.10.0
Is there anything I could to help you debug it?
( stefanovazzocell@gmail.com - I can send you some screenshots or db dumps if you want)

**Comment by stefanovazzocell** [comment]
Yes, no result from that. I have not figure out why but sometimes the issue seems to solve itself (?) I do not know how.
Also, the article was created on 1.10.0

**Comment by kevinansfield** [comment]
Ok, so you're actually talking about the order of posts that are _supposed_ to be drafts? In that case it is this issue, it's still open which means we're aware of it and it's not fixed yet ;-) There's a suggested solution in the messages above, PR's are welcome 😄

**Comment by stefanovazzocell** [comment]
I'm talking about post that are supposed published (and appearing into the blog (readable/published/public) that are still listed as draft in the admin UI (/ghost/*)

**Comment by kevinansfield** [comment]
Ok, that's not related to either of these issues. It sounds like a caching problem rather than an bug in Ghost, I would suggest swinging by our [slack channel](https://slack.ghost.org) to get some help diagnosing it, if it turns out it is a bug in Ghost a separate issue can be opened.

**Comment by 1c7** [comment]
wow. this issue post at May 2017, still not solve now(2018 May 1)
Can anyone please fix this?
